language: node_js
node_js:
  - '0.10'
  - '0.11'
  - iojs

matrix:
  fast_finish: true
  allow_failures:
    - node_js: iojs
  
cache:
  directories:
    - node_modules
    - bower_components
before_script:
  - npm install -g bower grunt-cli
  - gem install sass
  - bower install